services:
  app:
    build: ./api
    ports:
      - 80:80
    depends_on:
      - companydb

  companydb:
    image: mysql:8
    volumes:
      - "./ddl_script:/docker-entrypoint-initdb.d"
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/dbrootpass
      - MYSQL_PASSWORD_FILE=/run/secrets/dbrootuser
      - MYSQL_USER=jechu
    secrets:
      - dbrootpass
      - dbrootuser
    expose: 
      - 3306
  
secrets:
  dbrootpass:
      file: db_root_pass.txt
  dbrootuser:
      file: db_user_pass.txt

volumes:
  mysql_data: